ProdcutSite/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProductSite.Domain.Entities;

namespace ProdcutSite.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; } 
        public string ReturnUrl { get; set; }         
    }
}

ProdcutSite/Models/PagingInfo.cs
using System;


namespace ProdcutSite.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemPerPages { get; set; }
        public int CurrentPages { get; set; }

        public int TotalPages
        {
            get
            {
                return (int) Math.Ceiling((decimal) TotalItems/ItemPerPages);
            }
        }

    }
}

ProdcutSite/Models/ProductsListViewModel.cs
using System.Collections.Generic;
using ProductSite.Domain.Entities;

namespace ProdcutSite.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }   
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCatagory { get; set; }
    }
}

ProdcutSite/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using ProdcutSite.Models;
using ProductSite.Domain.Abstract;
using ProductSite.Domain.Entities;

namespace ProdcutSite.Controllers
{
    public class CartController : Controller
    {
        //
        // GET: /Cart/
        private IProductsRepository repository;
        private IOrderProcessor orderProcessor; 
        public ViewResult Index(Cart cart ,string returnUrl)
        {
            return View(new CartIndexViewModel {Cart = cart, ReturnUrl = returnUrl});
        } 

        public  CartController(IProductsRepository repo , IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            } 
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails); cart.Clear(); return View("Completed");
            } 
            else
            {
                return View(shippingDetails);
            }
        } 

        public RedirectToRouteResult AddToCart(Cart cart ,int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId); 
            if (product != null)
            { 
                cart.AddItem(product, 1);
            } return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart ,int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            } 
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Summary(Cart cart)
        { 
            return View(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        } 
        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null) 
            { cart = new Cart();
                Session["Cart"] = cart; 
            }
            return cart;
        } 
    }
}

ProdcutSite/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using  ProductSite.Domain.Abstract ;
using  ProdcutSite.Models;

namespace ProdcutSite.Controllers
{
    public class NavController : Controller
    {
        private IProductsRepository repository;

        public  NavController(IProductsRepository repo)
        {
            repository = repo;
        }

        //public  PartialViewResult Menu(string catagory = null)
        //{
        //    IEnumerable<string> catagories = repository.Products
        //        .Select(x => x.Catagory)
        //        .Distinct()
        //        .OrderBy(x => x);
        //    return PartialView(catagories);
        //}

        public ViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category; 
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Catagory)
                .Distinct()
                .OrderBy(x => x); 
            return View(categories);
        } 
    }
}

ProdcutSite/Controllers/ProductController.cs
using System.Linq;
using System.Web.Mvc;
using ProdcutSite.Models;
using ProductSite.Domain.Abstract;

namespace ProdcutSite.Controllers
{
    public class ProductController : Controller
    {
        public int PageSize = 4; // We will change this later 
        private IProductsRepository repository;

        public ProductController(IProductsRepository repoParam)
        {
            repository = repoParam;
        }

        public ViewResult List(string catagory ,int page = 1)
        {
            ProductsListViewModel viewModel = new ProductsListViewModel
                {
                    Products = repository.Products
                    .Where(p => catagory == null || p.Catagory == catagory)
                    .OrderBy(p => p.ProductID)
                    .Skip((page - 1)*PageSize)
                    .Take(PageSize),
                    PagingInfo = new PagingInfo
                        {
                            CurrentPages = page,
                            ItemPerPages = PageSize,
                            TotalItems = catagory == null ? 
                            repository.Products.Count() : 
                            repository.Products.Where(e => e.Catagory == catagory).Count()                       
                        },
                        CurrentCatagory =  catagory
                };
            return View(viewModel); 

        } 
        //
        // GET: /Product/
        //public ActionResult List()
        //{
        //    return View(repository.Products);
        //}

    }
}

ProdcutSite/Views/Cart/Checkout.cshtml
@model ProductSite.Domain.Entities.ShippingDetails
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Checkout";
}
<h2>
    Checkout</h2>
Please enter your details, and we'll ship your goods right away!
@using (Html.BeginForm())
{    
     @Html.ValidationSummary() 
    <h3>
        Ship to</h3>     
    <div>
        Name: @Html.EditorFor(x => x.Name)</div>    
    <h3>
        Address</h3>     
    <div>
        Line 1: @Html.EditorFor(x => x.Line1)</div>     
    <div>
        Line 2: @Html.EditorFor(x => x.Line2)</div>     
    <div>
        Line 3: @Html.EditorFor(x => x.Line3)</div>     
    <div>
        City: @Html.EditorFor(x => x.City)</div>     
    <div>
        State: @Html.EditorFor(x => x.State)</div>     
    <div>
        Zip: @Html.EditorFor(x => x.Zip)</div>     
    <div>
        Country: @Html.EditorFor(x => x.Country)</div>     
    <h3>
        Options</h3>     
    <label>@Html.EditorFor(x => x.GiftWrap) Gift wrap these items</label>     
    <p align="center">
        <input class="actionButtons" type="submit" value="Complete order" /></p> 
}

ProdcutSite/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "SportsStore: Order Submitted";
}
<h2>
    Thanks!</h2>
Thanks for placing your order. We'll ship your goods as soon as possible. 

ProdcutSite/Views/Cart/Index.cshtml
@model ProdcutSite.Models.CartIndexViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Sports Store :Your Cart";
}
<h2>
    Your cart</h2>
<table width="90%" align="center">
    <thead>
        <tr>
            <th align="center">
                Quantity
            </th>
            <th align="left">
                Item
            </th>
            <th align="right">
                Price
            </th>
            <th align="right">
                Subtotal
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td align="center">@line.Quantity
                </td>
                <td align="left">@line.Product.Name
                </td>
                <td align="right">@line.Product.Price.ToString("c")
                </td>
                <td align="right">@((line.Quantity * line.Product.Price).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductID)
                        @Html.HiddenFor(x => x.ReturnUrl)    
                        <input class="actionButtons" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">
                Total:
            </td>
            <td align="right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<p align="center" class="actionButtons">
    <a href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout now", "Checkout")
</p>

ProdcutSite/Views/Cart/Summary.cshtml
@model ProductSite.Domain.Entities.Cart
@{
    Layout = null;
}
<div id="cart">
    <span class="caption"><b>Your cart:</b> @Model.Lines.Sum(x => x.Quantity) item(s), @Model.ComputeTotalValue().ToString("c")
    </span>
    @Html.ActionLink("Checkout", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, null)
</div>

ProdcutSite/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@{
    Layout = null;
}

@Html.ActionLink("Home", "List", "Product")
 @foreach (var link in Model)
 {
     @Html.RouteLink(link, new
         {
             controller = "Product",
             action = "List",
             category = link,
             page = 1
         },
                new { @class = link == ViewBag.SelectedCategory ? "selected" : null } 
         )
        
 }

ProdcutSite/Views/Product/List.cshtml
@using ProdcutSite.HtmlHelpers
@model ProdcutSite.Models.ProductsListViewModel
@{
    ViewBag.Title = "Products";
}
<h2>
    Products of Spacial Symbol
</h2>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@foreach (var p in Model.Products)
{
    Html.RenderPartial("ProductSummary", p);
}
@*@foreach (var p in Model.Products)
{
    <div class="item">
        <h3>
            @p.Name
        </h3>
        <h3>
            @p.Description
        </h3>
        <h4>
            @p.Price.ToString("C")
        </h4>
        <h4>
            @p.Catagory
        </h4>
    </div>
}*@
<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x  , catagory  = Model.CurrentCatagory}))
</div>

ProdcutSite/Views/Shared/ProductSummary.cshtml
@model ProductSite.Domain.Entities.Product
<div class="item">
    <h3>@Model.Name</h3>
    @Model.Description
       @using (Html.BeginForm("AddToCart", "Cart"))
       {
           @Html.HiddenFor(x => x.ProductID)
           if (Request.Url != null)
           {
               @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
           }
           <input type="submit" value="+ Add to cart" />
       } 
    <h4>@Model.Price.ToString("c")</h4>
</div>

ProdcutSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>
<body>
    <div id="header">
        @{Html.RenderAction("Summary", "Cart");}
        <div class="title">SPORTS STORE</div>
    </div>
    <div id="categories">
        @{ Html.RenderAction("Menu", "Nav"); }
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>